apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo # Whatever label contains this, will belong to this string will belong to this deployment
  template: # Configuration of the Pod within the configuration of the Deployment
    metadata:
      labels:
        app: mongo # Determines the identifier for all Pods created here
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017 # Found in the mongo dockerhub docs
        env: # Passing environment values
        - name: MONGO_INITDB_ROOT_USERNAME # Found in mongo dockerhub docs
          valueFrom: # A way of accessing values from another resource
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
          # value: my user # can do this plainly if we weren't taking from a secret.
        - name: MONGO_INITDB_ROOT_PASSWORD # Found in mongo dockerhub docs
          valueFrom: # A way of accessing values from another resource
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
          # value: my user # can do this plainly if we weren't taking from a secret.

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector: # How to find the right Pods to forward the to.
    app: mongo
  ports:
    - protocol: TCP
      port: 27017 # Sets the port of the service. Sometimes standard to make it the same as the targetPort.
      targetPort: 27017 # The port of the Pod we're targeting. Where the service should forward to.